### ISSUE TITLE
Not working with mopidy 2.x

### ISSUE THREAD

**Issue by jpswade** [HeadspringLabs/mopidy-qsaver#4]
> Mopidy extension that maintains your current queue even when the server restarts

This does not happen.
# Steps to reproduce

```
PLAY_LIST=`mpc lsplaylists | head -n 1`
mpc load "${PLAY_LIST}"
mpc play
sudo reboot
```
# Debug information

```
pi@raspberrypi:~ $ mopidy --version
Mopidy 2.0.1
pi@raspberrypi:~ $ pip show Mopidy-Qsaver

---
Metadata-Version: 2.0
Name: Mopidy-Qsaver
Version: 0.2.6
Summary: Mopidy extension to persist queue across server restarts
Home-page: https://github.com/bardoloi/mopidy-qsaver
Author: Vishal Bardoloi
Author-email: v.bardoloi@gmail.com
License: Apache License, Version 2.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: Mopidy, Pykka, setuptools
Classifiers:
  Environment :: No Input/Output (Daemon)
  Intended Audience :: End Users/Desktop
  License :: OSI Approved :: Apache Software License
  Operating System :: OS Independent
  Programming Language :: Python :: 2
  Topic :: Multimedia :: Sound/Audio :: Players
Entry-points:
  [mopidy.ext]
  qsaver = mopidy_qsaver:Extension
pi@raspberrypi:~ $ sudo cat /etc/mopidy/mopidy.conf
[core]
cache_dir = /var/cache/mopidy
config_dir = /etc/mopidy
data_dir = /var/lib/mopidy

[logging]
config_file = /etc/mopidy/logging.conf
debug_file = /var/log/mopidy/mopidy-debug.log

[local]
data_dir = /var/lib/mopidy/local
media_dir = /var/lib/mopidy/media
enabled = true

[m3u]
playlists_dir = /var/lib/mopidy/playlists

[http]
enabled = true
hostname = 0.0.0.0
port = 6680
static_dir = ""
zeroconf = Mopidy HTTP server on raspberrypi

[qsaver]
enabled = true
backup_file = ./tracklist_backup.json
[spotify]
enabled = true
username = 
password = 
bitrate = 160
[gmusic]
enabled = false
[tunein]
enabled = true
[podcast]
enabled = true
[internetarchive]
enabled = true
[youtube]
enabled = true
[audioaddict]
enabled = false
quality = 40k
difm = false
radiotunes = false
rockradio = false
jazzradio = false
frescaradio = false
[somafm]
enabled = true
[soundcloud]
enabled = false
[audio]
mixer_volume = 85
[dirble]
enabled = false
[scrobbler]
enabled = false
[subsonic]
enabled = false
ssl = no
```

**Comment by lilmike** [comment]
Hi,
I have (possibly) the same problem. I get a traceback:

ERROR    Unhandled exception in QSaverFrontend (urn:uuid:a01d6bb8-a300-4981-8690-c57698c57287):
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pykka/actor.py", line 191, in _actor_loop
    self.on_start()
  File "/usr/lib/python2.7/site-packages/mopidy_qsaver/frontend.py", line 43, in on_start
    self.restoreQueue()
  File "/usr/lib/python2.7/site-packages/mopidy_qsaver/frontend.py", line 35, in restoreQueue
    uri_list = eval(uri_list_str)  # convert to array
  File "<string>", line 0

    ^
SyntaxError: unexpected EOF while parsing

-Michael.

**Comment by tudor2004** [comment]
Hi, is there any alternativ solution to this exception? Indeed it seems not to work with mopidy 2.0?

**Comment by hulahomer** [comment]
It looks like this has been integrated upstream into Mopidy https://github.com/mopidy/mopidy/issues/310

So my suggestion would be update to 2.1 where this was merged and utilize the built in feature.
